apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-app
  labels:
    app: discovery-service-app
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: discovery-service-app
  template:
    metadata:
      labels:
        app: discovery-service-app
    spec:
      containers:
        - name: discovery-service-app
          image: janescience/discovery-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
